(() => {
 'use strict';
 let data=structuredClone(window.NEXO_PEOPLE||{email:'ge.nino183@uniandes.edu.co',items:[]}),selected=null,formDirty=false,listDirty=false;
 const field=id=>document.getElementById(id),form=field('people-form'),notice=text=>field('editor-notice').textContent=text;
 const labels={team:'Equipo',collaborator:'Colaborador'};
 const local=(value,lang)=>typeof value==='string'?value:(value?.[lang]||'');
 const safeURL=value=>{try{return ['http:','https:'].includes(new URL(value).protocol);}catch{return false;}};
 const safePDF=value=>/^(?:assets\/(?:[a-zA-Z0-9_ .-]+\/)*)?[a-zA-Z0-9_ .-]+\.pdf$/i.test(value||'')&&!value.includes('..');
 function validate(item){if(!item.id||!item.name||!labels[item.category]||!local(item.role,'en')||!local(item.role,'es'))throw new Error('Completa el nombre, la categoría y el cargo en ambos idiomas.');if(item.image&&(!/^assets\/[a-zA-Z0-9/_ .-]+\.(jpg|jpeg|png|webp|svg)$/i.test(item.image)||item.image.includes('..')))throw new Error('Usa una foto en assets/, como assets/people/nombre.jpg.');for(const key of ['url','linkedin','scholar'])if(item[key]&&!safeURL(item[key]))throw new Error('Los enlaces de perfil, LinkedIn y Google Scholar deben comenzar con https:// o http://.');if(item.cv&&!safeURL(item.cv)&&!safePDF(item.cv))throw new Error('Usa un enlace https:// o un PDF local, como Resume_and_CV.pdf o assets/people/cv.pdf.');}
 function render(){field('editor-list').replaceChildren();field('editor-total').textContent=`(${data.items.length})`;data.items.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='editor-list-button'+(item.id===selected?' active':'');button.textContent=item.name;button.dataset.id=item.id;const category=document.createElement('span');category.textContent=labels[item.category];button.append(category);button.addEventListener('click',()=>{if(formDirty){notice('Guarda el formulario antes de seleccionar otra persona.');return;}load(item.id);});field('editor-list').append(button);});}
 function load(id){selected=id;const item=data.items.find(p=>p.id===id);form.reset();field('form-title').textContent=item?'Editar persona':'Agregar una persona';for(const key of ['name','institution','image','url','linkedin','scholar','cv'])field('person-'+key).value=item?.[key]||'';field('person-category').value=item?.category||'team';for(const key of ['role','bio'])for(const lang of ['en','es'])field(key+'-'+lang).value=local(item?.[key],lang);field('form-error').hidden=true;field('delete-confirm').hidden=true;field('delete-person').hidden=!item;formDirty=false;render();}
 form.addEventListener('input',()=>formDirty=true);form.addEventListener('submit',event=>{event.preventDefault();try{const item={...(data.items.find(p=>p.id===selected)||{}),id:selected||'person-'+crypto.randomUUID(),category:field('person-category').value};for(const key of ['name','institution','image','url','linkedin','scholar','cv'])item[key]=field('person-'+key).value.trim();for(const key of ['role','bio'])item[key]={en:field(key+'-en').value.trim(),es:field(key+'-es').value.trim()};validate(item);const index=data.items.findIndex(p=>p.id===selected);if(index<0)data.items.push(item);else data.items[index]=item;listDirty=true;load(item.id);notice('Persona guardada en la lista. Descarga el archivo para conservar los cambios.');}catch(error){field('form-error').textContent=error.message;field('form-error').hidden=false;}});
 field('add-person').addEventListener('click',()=>{if(formDirty){notice('Guarda el formulario antes de agregar otra persona.');return;}load(null);field('person-name').focus();});
 function serialize(){return '/* Shared people catalog for both languages. */\nwindow.NEXO_PEOPLE = '+JSON.stringify(data,null,2)+';\n';}
 field('export-people').addEventListener('click',()=>{if(formDirty){notice('Primero selecciona Guardar en la lista.');return;}const url=URL.createObjectURL(new Blob([serialize()],{type:'application/javascript;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='people-data.js';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);listDirty=false;notice('Archivo descargado. Reemplaza people-data.js y recarga ambas versiones.');});
 field('import-people').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(formDirty||listDirty){notice('Descarga tus cambios antes de abrir otro archivo.');event.target.value='';return;}try{const text=await file.text(),match=text.match(/window\.NEXO_PEOPLE\s*=\s*([\s\S]*?)\s*;?\s*$/);if(!match)throw new Error('Selecciona un archivo people-data.js válido.');const parsed=JSON.parse(match[1].replace(/;\s*$/,''));if(!Array.isArray(parsed.items)||typeof parsed.email!=='string')throw new Error('El archivo debe incluir email e items.');const ids=new Set();for(const item of parsed.items){validate(item);if(ids.has(item.id))throw new Error('Hay identificadores repetidos.');ids.add(item.id);}data=parsed;listDirty=false;load(data.items[0]?.id||null);notice('Archivo cargado.');}catch(error){notice(error.message);}finally{event.target.value='';}});
 field('delete-person').addEventListener('click',()=>field('delete-confirm').hidden=false);field('cancel-delete').addEventListener('click',()=>field('delete-confirm').hidden=true);field('confirm-delete').addEventListener('click',()=>{data.items=data.items.filter(p=>p.id!==selected);listDirty=true;load(data.items[0]?.id||null);notice('Persona eliminada de la lista. Descarga el archivo para conservar el cambio.');});
 window.addEventListener('beforeunload',event=>{if(formDirty||listDirty){event.preventDefault();event.returnValue='';}});window.NEXO_EDITOR={serialize};load(data.items[0]?.id||null);
})();
